-- Accra hospitals: identity records.
--
-- Bed, ICU and oxygen figures are deliberately absent. Those numbers are not
-- public information and must come from the hospitals themselves, so every row
-- starts as 'unreported' and the map shows a dash rather than a zero.
--
-- Generated by data/generate_seed.py. Edit hospitals.geojson, not this file.

insert into hospitals
  (name, type, region_area, address, main_phone, location,
   notes, listing_status, location_confidence, hefra_licence)
values
  ('Korle-Bu Teaching Hospital', 'Teaching', 'Korle-Bu', 'Guggisberg Ave, Korle-Bu, Accra', '+233 302 665401', st_point(-0.2264, 5.5359)::geography, 'Identity verified from public directories. Bed figures awaiting first hospital report.', 'published', 'verified', null),
  ('Greater Accra Regional Hospital (Ridge)', 'Government', 'Ridge', 'Castle Rd, Ridge, Accra', null, st_point(-0.198676, 5.561618)::geography, '420-bed capacity per public records. Coordinates verified. Phone not found in public sources.', 'published', 'verified', null),
  ('University of Ghana Teaching Hospital', 'Teaching', 'Legon', 'University of Ghana Campus, Legon, Accra', null, st_point(-0.187, 5.65)::geography, '617-bed facility per public records. Coordinates approximate, verify before deployment.', 'published', 'approximate', null),
  ('37 Military Hospital', 'Government', 'Cantonments', 'Liberation Road, Accra', null, st_point(-0.1855, 5.581)::geography, 'Coordinates approximate, verify before deployment. Phone not found in public sources.', 'published', 'approximate', null),
  ('La General Hospital', 'Government', 'La', 'La, Accra', null, st_point(-0.1665, 5.5554)::geography, 'Formerly La Polyclinic. Coordinates verified from public reference.', 'published', 'verified', null),
  ('Lister Hospital', 'Private', 'East Airport', 'Nii Martey Tsuru St, East Airport, off Spintex Road, Accra', '+233 303 409030', st_point(-0.165, 5.605)::geography, 'Coordinates approximate, verify before deployment.', 'published', 'approximate', null),
  ('Nyaho Medical Centre', 'Private', 'Airport Residential Area', '35 Aviation Rd, Airport Residential Area, Accra', '+233 302 775341', st_point(-0.177, 5.604)::geography, 'Coordinates approximate, verify before deployment.', 'published', 'approximate', null),
  ('Trust Hospital (Osu Main)', 'Private', 'Osu', 'Osu Main, Accra', '+233 302 761974', st_point(-0.183, 5.556)::geography, 'Coordinates approximate, verify before deployment.', 'published', 'approximate', null),
  ('Police Hospital', 'Government', 'Cantonments', 'Ring Road East, Accra', null, st_point(-0.1889, 5.5747)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Achimota Hospital', 'Government', 'Achimota', 'Achimota, Accra', null, st_point(-0.2264, 5.6122)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Maamobi General Hospital', 'Government', 'Maamobi', 'Maamobi, Accra', null, st_point(-0.2011, 5.5975)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Tema General Hospital', 'Government', 'Tema', 'Hospital Road, Tema', null, st_point(0.0143, 5.6698)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Ga East Municipal Hospital', 'Government', 'Abokobi', 'Abokobi, Ga East, Accra', null, st_point(-0.1878, 5.705)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Princess Marie Louise Children''s Hospital', 'Government', 'Adabraka', 'Castle Road, Adabraka, Accra', null, st_point(-0.2089, 5.5528)::geography, 'Paediatric specialist hospital. Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Mamprobi Polyclinic', 'Government', 'Mamprobi', 'Mamprobi, Accra', null, st_point(-0.2358, 5.5386)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Kaneshie Polyclinic', 'Government', 'Kaneshie', 'Kaneshie, Accra', null, st_point(-0.2361, 5.5644)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Dansoman Polyclinic', 'Government', 'Dansoman', 'Dansoman, Accra', null, st_point(-0.26, 5.5442)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Adabraka Polyclinic', 'Government', 'Adabraka', 'Adabraka, Accra', null, st_point(-0.2094, 5.5589)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('The Bank Hospital', 'Private', 'Cantonments', 'Cantonments, Accra', null, st_point(-0.1758, 5.5872)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Euracare Advanced Diagnostic and Heart Centre', 'Private', 'Airport Residential Area', 'Airport Residential Area, Accra', null, st_point(-0.1786, 5.6047)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('C&J Medicare Hospital', 'Private', 'Kaneshie', 'Kaneshie, Accra', null, st_point(-0.2372, 5.5697)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null),
  ('Pentecost Hospital', 'Private', 'Madina', 'Madina, Accra', null, st_point(-0.1667, 5.6836)::geography, 'Coordinates approximate. Verify against the site and the HeFRA licensed register before operational use.', 'published', 'approximate', null);
