#!/usr/bin/env python3
"""
Regenerate supabase/seed.sql from the GeoJSON dataset.

The GeoJSON stays the source of truth for hospital identity, so edits are made
there and the SQL is derived rather than maintained by hand.

Usage:
    python3 data/generate_seed.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "hospitals.geojson"
TARGET = ROOT / "supabase" / "seed.sql"

HEADER = """-- Accra hospitals: identity records.
--
-- Bed, ICU and oxygen figures are deliberately absent. Those numbers are not
-- public information and must come from the hospitals themselves, so every row
-- starts as 'unreported' and the map shows a dash rather than a zero.
--
-- Generated by data/generate_seed.py. Edit hospitals.geojson, not this file.

insert into hospitals
  (name, type, region_area, address, main_phone, location,
   notes, listing_status, location_confidence, hefra_licence)
values
"""


def quote(value):
    """SQL string literal, or NULL for anything empty."""
    if value is None or value == "":
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def main():
    with SOURCE.open(encoding="utf-8") as handle:
        doc = json.load(handle)

    rows = []
    for feature in doc.get("features", []):
        props = feature["properties"]
        lon, lat = feature["geometry"]["coordinates"]

        if not (-0.6 < lon < 0.3 and 5.3 < lat < 6.0):
            raise SystemExit(
                f"{props.get('hospital_name')} sits outside Greater Accra: {lon},{lat}"
            )

        rows.append(
            "  ({name}, {type}, {area}, {addr}, {phone}, "
            "st_point({lon}, {lat})::geography, {notes}, {listing}, {conf}, {licence})".format(
                name=quote(props.get("hospital_name")),
                type=quote(props.get("hospital_type")),
                area=quote(props.get("region_area")),
                addr=quote(props.get("address")),
                phone=quote(props.get("main_phone")),
                lon=lon,
                lat=lat,
                notes=quote(props.get("notes")),
                listing=quote(props.get("listing_status") or "published"),
                conf=quote(props.get("location_confidence") or "approximate"),
                licence=quote(props.get("hefra_licence")),
            )
        )

    TARGET.write_text(HEADER + ",\n".join(rows) + ";\n", encoding="utf-8")
    print(f"wrote {len(rows)} hospital rows to {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
